<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Achievements\AFE1_Improvised_Explosives_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_I_Think_They_Like_Me_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Purge_The_Unclean_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Spilled_Milk_Complete.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Demolisher.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Doc.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Gunner.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Lancer.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Phalanx.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Recon.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Technician.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Achievements\AFE1_High_Voltage_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Improvised_Explosives_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_I_Think_They_Like_Me_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Purge_The_Unclean_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Spilled_Milk_Complete.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Demolisher.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Doc.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Gunner.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Lancer.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Phalanx.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Recon.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Technician.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
