<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Achievements\AFE1_All_My_Personal_Friends_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Anti_Mutation_Station_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Art_Gallery_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_A_Personal_Friend_of_Mine_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_A_Stand_Up_Fight_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Burn_Em_Out_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_CMISRS_Asset_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_CMISRS_Resource_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Confidence_Course_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Didnt_Break_a_Sweat_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Expeditionary_Service_Ribbon_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Express_Yourself_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Fashion_Team_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Fully_Rigged_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Giants_in_the_Earth_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Glorified_Toasters_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Got_All_I_Need_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Improvised_Explosives_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Its_A_Bug_Hunt_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Its_a_Cover_Not_a_Hat_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Its_Camouflage_on_Some_Planet_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_I_Cant_Lie_About_Your_Chances_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_I_Think_They_Like_Me_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Keen_Eye_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Kitted_Out_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_LV-895_Campaign_Medal_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_My_Kind_of_Crazy_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Nukes_Knives_AND_Sharp_Sticks_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Overwhelming_Confidence_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Pod_Popper_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Priority_One_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Promise_of_a_Flower_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Ready_for_Anything_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Red_Makes_It_Shoot_Faster_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Specialist_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_State_of_the_Art_Firepower_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Supportive_Squad_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_The_Gift_of_Fire_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_The_Only_Way_to_be_Sure_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Those_Things_Were_Huge_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Tower_Defense_Complete.png" />
    <None Remove="Resources\Achievements\AFE1_Trigger_Discipline_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Another_Bug_Hunt_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Canary_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Custom_Made_Marine_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Decommission_Mission_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Fervent_Warrior_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Fully_Loaded_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Hardened_Trooper_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Head_Hunter_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Hell_and_Back_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Its_A_Rescue_Mission_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Maxed_Out_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Next_Top_Marine_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Noble_Soldier_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Not_Just_For_Decoration_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Overly_Attached_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Pure_Professionals_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Purge_The_Unclean_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Reckoning_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Seasoned_Veteran_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Spilled_Milk_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_The_Story_of_the_Quarry_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Voided_Warranty_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Wave_Goodbye_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Well_Stocked_Arsenal_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Worst_Party_Ever_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Worthiness_Tested_Complete.png" />
    <None Remove="Resources\Achievements\AFE2_Yellow_Makes_It_Shoot_Better_Complete.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Demolisher.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Doc.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Gunner.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Lancer.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Phalanx.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Recon.png" />
    <None Remove="Resources\ClassIcons\AFE1_Class_Technician.png" />
    <None Remove="Resources\ClassIcons\AFE2_Class_Custom.png" />
    <None Remove="Resources\ClassIcons\AFE2_Class_Demolisher.png" />
    <None Remove="Resources\ClassIcons\AFE2_Class_Doc.png" />
    <None Remove="Resources\ClassIcons\AFE2_Class_Gunner.png" />
    <None Remove="Resources\ClassIcons\AFE2_Class_Lancer.png" />
    <None Remove="Resources\ClassIcons\AFE2_Class_Technician.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Achievements\AFE1_Fashion_Team_Complete.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Achievements\AFE1_All_My_Personal_Friends_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Anti_Mutation_Station_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Art_Gallery_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_A_Personal_Friend_of_Mine_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_A_Stand_Up_Fight_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Burn_Em_Out_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_CMISRS_Asset_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_CMISRS_Resource_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Confidence_Course_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Didnt_Break_a_Sweat_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Expeditionary_Service_Ribbon_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Express_Yourself_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Fully_Rigged_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Giants_in_the_Earth_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Glorified_Toasters_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Got_All_I_Need_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_High_Voltage_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Improvised_Explosives_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Its_A_Bug_Hunt_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Its_a_Cover_Not_a_Hat_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Its_Camouflage_on_Some_Planet_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_I_Cant_Lie_About_Your_Chances_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_I_Think_They_Like_Me_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Keen_Eye_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Kitted_Out_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_LV-895_Campaign_Medal_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_LV-895_Service_Ribbon_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_My_Kind_of_Crazy_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Nukes_Knives_AND_Sharp_Sticks_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Overwhelming_Confidence_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Pod_Popper_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Priority_One_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Promise_of_a_Flower_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Ready_for_Anything_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Red_Makes_It_Shoot_Faster_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Reticulum_Theater_Medal_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Specialist_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_State_of_the_Art_Firepower_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Supportive_Squad_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Suturing_Expert_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_The_Gift_of_Fire_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_The_Only_Way_to_be_Sure_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Those_Things_Were_Huge_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Tower_Defense_Complete.png" />
    <Resource Include="Resources\Achievements\AFE1_Trigger_Discipline_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Another_Bug_Hunt_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Canary_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Custom_Made_Marine_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Decommission_Mission_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Fervent_Warrior_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Hardened_Trooper_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Hell_and_Back_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_How_Do_You_See_Out_Of_These_Things_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Fully_Loaded_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Head_Hunter_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Its_A_Rescue_Mission_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Legionnaires_Service_Medal_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Maxed_Out_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Next_Top_Marine_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Noble_Soldier_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Not_Just_For_Decoration_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Overly_Attached_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Pure_Professionals_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Purge_The_Unclean_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Reckoning_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Seasoned_Veteran_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Spilled_Milk_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_The_Story_of_the_Quarry_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Voided_Warranty_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Wave_Goodbye_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Welcoming_Committee_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Well_Stocked_Arsenal_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Worst_Party_Ever_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Worthiness_Tested_Complete.png" />
    <Resource Include="Resources\Achievements\AFE2_Yellow_Makes_It_Shoot_Better_Complete.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Demolisher.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Doc.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Gunner.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Lancer.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Phalanx.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Recon.png" />
    <Resource Include="Resources\ClassIcons\AFE1_Class_Technician.png" />
    <Resource Include="Resources\ClassIcons\AFE2_Class_Custom.png" />
    <Resource Include="Resources\ClassIcons\AFE2_Class_Demolisher.png" />
    <Resource Include="Resources\ClassIcons\AFE2_Class_Doc.png" />
    <Resource Include="Resources\ClassIcons\AFE2_Class_Gunner.png" />
    <Resource Include="Resources\ClassIcons\AFE2_Class_Lancer.png" />
    <Resource Include="Resources\ClassIcons\AFE2_Class_Technician.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
